---
language: python
python:
- "3.7"
before_install:
- sudo apt-get install -y libudev-dev curl wget unzip
- mkdir -p ./custom_components/hacs
install:
- |
  curl -s https://api.github.com/repos/hacs/integration/releases/latest |
  grep -oP '"browser_download_url": "\K(.*)(?=")' | wget -i -
- unzip -q hacs.zip -d ./custom_components/hacs
- mv travis_secrets.yaml secrets.yaml
- pip3 install homeassistant
script:
- hass -c . --script check_config
