---
## Home Assistant Main Config
homeassistant: !include homeassistant.yaml

## Home Assistant Components Enabled
# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/api/
api:

# https://home-assistant.io/components/http/
http:
  login_attempts_threshold: 100

## Home Assistant Core Components Global
# https://www.home-assistant.io/components/logger/
logger:
  default: error

# https://www.home-assistant.io/components/notify/
# and
# https://www.home-assistant.io/components/notify.group/
notify:

## General Automation
# https://www.home-assistant.io/components/automation/
automation:
