---
## Home Assistant Main Config
homeassistant:
  customize: !include customize.yaml

  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

## Home Assistant Components Enabled
# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/api/
api:

# https://home-assistant.io/components/http/
http:
  login_attempts_threshold: 100

## Home Assistant Core Components Global
# https://www.home-assistant.io/components/logger/
logger:
  default: error

# https://www.home-assistant.io/components/notify/
# and
# https://www.home-assistant.io/components/notify.group/
notify:

## General Automation
# https://www.home-assistant.io/components/automation/
automation:
  - alias: Update Available Notification
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.notify
      data:
        message: "Update for Home Assistant is available."
        title: "Update"
